export const GROUP_RANKING_TABLE = {
  A: {
    Canada: {
      ISOCode: "CAN",
      GamesPlayed: 0,
      Wins: 0,
      Losses: 0,
      PointsForwarded: 0,
      PointsAccepted: 0,
      PointDifference: 0,
      Points: 0,
    },
    Australia: {
      ISOCode: "AUS",
      GamesPlayed: 0,
      Wins: 0,
      Losses: 0,
      PointsForwarded: 0,
      PointsAccepted: 0,
      PointDifference: 0,
      Points: 0,
    },
    Greece: {
      ISOCode: "GRE",
      GamesPlayed: 0,
      Wins: 0,
      Losses: 0,
      PointsForwarded: 0,
      PointsAccepted: 0,
      PointDifference: 0,
      Points: 0,
    },
    Spain: {
      ISOCode: "ESP",
      GamesPlayed: 0,
      Wins: 0,
      Losses: 0,
      PointsForwarded: 0,
      PointsAccepted: 0,
      PointDifference: 0,
      Points: 0,
    },
  },
  B: {
    Germany: {
      ISOCode: "GER",
      GamesPlayed: 0,
      Wins: 0,
      Losses: 0,
      PointsForwarded: 0,
      PointsAccepted: 0,
      PointDifference: 0,
      Points: 0,
    },
    France: {
      ISOCode: "FRA",
      GamesPlayed: 0,
      Wins: 0,
      Losses: 0,
      PointsForwarded: 0,
      PointsAccepted: 0,
      PointDifference: 0,
      Points: 0,
    },
    Brasil: {
      ISOCode: "BRA",
      GamesPlayed: 0,
      Wins: 0,
      Losses: 0,
      PointsForwarded: 0,
      PointsAccepted: 0,
      PointDifference: 0,
      Points: 0,
    },
    Japan: {
      ISOCode: "JPN",
      GamesPlayed: 0,
      Wins: 0,
      Losses: 0,
      PointsForwarded: 0,
      PointsAccepted: 0,
      PointDifference: 0,
      Points: 0,
    },
  },
  C: {
    USA: {
      ISOCode: "USA",
      GamesPlayed: 0,
      Wins: 0,
      Losses: 0,
      PointsForwarded: 0,
      PointsAccepted: 0,
      PointDifference: 0,
      Points: 0,
    },
    Serbia: {
      ISOCode: "SRB",
      GamesPlayed: 0,
      Wins: 0,
      Losses: 0,
      PointsForwarded: 0,
      PointsAccepted: 0,
      PointDifference: 0,
      Points: 0,
    },
    SouthSudan: {
      Team: "Južni Sudan",
      ISOCode: "SSD",
      GamesPlayed: 0,
      Wins: 0,
      Losses: 0,
      PointsForwarded: 0,
      PointsAccepted: 0,
      PointDifference: 0,
      Points: 0,
    },
    PuertoRico: {
      ISOCode: "PRI",
      GamesPlayed: 0,
      Wins: 0,
      Losses: 0,
      PointsForwarded: 0,
      PointsAccepted: 0,
      PointDifference: 0,
      Points: 0,
    },
  },
};
